"""test running migrations

Revision ID: 037fb632e827
Revises: de7e31fb5072
Create Date: 2024-08-04 21:00:38.079337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037fb632e827'
down_revision = 'de7e31fb5072'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
