"""test running migrations

Revision ID: 0c9ab180ef8f
Revises: 21d8358a8821
Create Date: 2024-08-04 21:13:19.598540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9ab180ef8f'
down_revision = '21d8358a8821'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
