"""test running migrations

Revision ID: 11a87b66088e
Revises: 87697b7750b0
Create Date: 2024-08-04 21:11:54.292282

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "11a87b66088e"
down_revision = "87697b7750b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
