"""test running migrations

Revision ID: 12bfc671da45
Revises: 482f213e46bd
Create Date: 2024-09-09 15:57:52.077425

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "12bfc671da45"
down_revision = "482f213e46bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
