"""test running migrations

Revision ID: 1475e788512f
Revises: d2af7d3c112e
Create Date: 2024-09-09 16:02:43.501952

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1475e788512f"
down_revision = "d2af7d3c112e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
