"""test running migrations

Revision ID: 192476dd0391
Revises: 21d987f6b0f0
Create Date: 2024-09-09 15:43:31.586594

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "192476dd0391"
down_revision = "21d987f6b0f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
