"""test running migrations

Revision ID: 1dd8c66f8162
Revises: d3cac145aca6
Create Date: 2024-07-31 21:53:50.841988

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1dd8c66f8162"
down_revision = "d3cac145aca6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
