"""test running migrations

Revision ID: 21d8358a8821
Revises: 11a87b66088e
Create Date: 2024-08-04 21:12:16.878448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d8358a8821'
down_revision = '11a87b66088e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
