"""test running migrations

Revision ID: 226540335ada
Revises: 12bfc671da45
Create Date: 2024-09-09 15:59:11.506869

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "226540335ada"
down_revision = "12bfc671da45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
