"""test running migrations

Revision ID: 2a54955da4de
Revises: 7ce240fa3134
Create Date: 2024-08-04 21:25:02.447773

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2a54955da4de"
down_revision = "7ce240fa3134"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
