"""test running migrations

Revision ID: 482f213e46bd
Revises: 50072fad7eb1
Create Date: 2024-09-09 15:47:45.730520

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "482f213e46bd"
down_revision = "50072fad7eb1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
