"""test running migrations

Revision ID: 50072fad7eb1
Revises: e38526ec3682
Create Date: 2024-09-09 15:44:44.525911

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "50072fad7eb1"
down_revision = "e38526ec3682"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
