"""test running migrations

Revision ID: 7ce240fa3134
Revises: 0c9ab180ef8f
Create Date: 2024-08-04 21:14:13.633048

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7ce240fa3134"
down_revision = "0c9ab180ef8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
