"""test running migrations

Revision ID: 87697b7750b0
Revises: 037fb632e827
Create Date: 2024-08-04 21:05:32.829732

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "87697b7750b0"
down_revision = "037fb632e827"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
