"""test running migrations

Revision ID: d2af7d3c112e
Revises: 226540335ada
Create Date: 2024-09-09 16:01:03.948271

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d2af7d3c112e"
down_revision = "226540335ada"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
