"""test running migrations

Revision ID: d3cac145aca6
Revises: 56c584f2ab77
Create Date: 2024-07-31 21:53:22.716478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cac145aca6'
down_revision = '56c584f2ab77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
