"""test running migrations

Revision ID: de7e31fb5072
Revises: 1dd8c66f8162
Create Date: 2024-08-04 20:55:00.621696

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "de7e31fb5072"
down_revision = "1dd8c66f8162"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
