"""test running migrations

Revision ID: e38526ec3682
Revises: 192476dd0391
Create Date: 2024-09-09 15:43:44.896547

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e38526ec3682"
down_revision = "192476dd0391"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
