"""test running migrations

Revision ID: 13d013367322
Revises: a8a757df6450
Create Date: 2024-07-04 21:51:24.318224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d013367322'
down_revision = 'a8a757df6450'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
