"""test running migrations

Revision ID: 161ef16420e6
Revises: 2256c12b3d77
Create Date: 2024-09-13 14:59:58.561567

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "161ef16420e6"
down_revision = "2256c12b3d77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
