"""test running migrations

Revision ID: 197aaaa2a36f
Revises: 1e05c3cd2346
Create Date: 2024-09-13 15:19:51.763442

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "197aaaa2a36f"
down_revision = "1e05c3cd2346"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
