"""test running migrations

Revision ID: 1e05c3cd2346
Revises: 3524e07e15ef
Create Date: 2024-09-13 15:18:28.766787

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1e05c3cd2346"
down_revision = "3524e07e15ef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
