"""test running migrations

Revision ID: 2256c12b3d77
Revises: 44349e970c8d
Create Date: 2024-09-13 14:56:29.803032

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2256c12b3d77"
down_revision = "44349e970c8d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
