"""test running migrations

Revision ID: 2c1d78ade0d2
Revises: 161ef16420e6
Create Date: 2024-09-13 15:07:19.091656

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2c1d78ade0d2"
down_revision = "161ef16420e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
