"""test running migrations

Revision ID: 2c77c90eb035
Revises: 6024ba911b49
Create Date: 2024-08-27 15:04:14.411349

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2c77c90eb035"
down_revision = "6024ba911b49"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
