"""test running migrations

Revision ID: 2db40fa383c3
Revises: 6357d524190c
Create Date: 2024-08-29 16:27:05.557100

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2db40fa383c3"
down_revision = "6357d524190c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
