"""test running migrations

Revision ID: 3524e07e15ef
Revises: c02f926fad03
Create Date: 2024-09-13 15:17:02.357710

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3524e07e15ef"
down_revision = "c02f926fad03"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
