"""test running migrations

Revision ID: 3cada3b1b98f
Revises: 44c3b669c42b
Create Date: 2024-09-13 15:12:22.340500

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3cada3b1b98f"
down_revision = "44c3b669c42b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
