"""test running migrations

Revision ID: 44349e970c8d
Revises: f5a1ce277426
Create Date: 2024-09-13 14:49:53.718590

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "44349e970c8d"
down_revision = "f5a1ce277426"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
