"""test running migrations

Revision ID: 44c3b669c42b
Revises: 2c1d78ade0d2
Create Date: 2024-09-13 15:10:16.815599

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "44c3b669c42b"
down_revision = "2c1d78ade0d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
