"""test running migrations

Revision ID: 486f84a71707
Revises: 97ffc145ad49
Create Date: 2024-07-13 13:59:57.916329

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "486f84a71707"
down_revision = "97ffc145ad49"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
