"""test running migrations

Revision ID: 4ae93cf5b509
Revises: 748419f23c93
Create Date: 2024-09-13 15:23:00.908694

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "4ae93cf5b509"
down_revision = "748419f23c93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
