"""test running migrations

Revision ID: 511671b15aec
Revises: 486f84a71707
Create Date: 2024-07-13 14:00:19.692898

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "511671b15aec"
down_revision = "486f84a71707"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
