"""test running migrations

Revision ID: 523419c1423c
Revises: ec5d1c7ca9cf
Create Date: 2024-07-04 21:46:09.555522

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "523419c1423c"
down_revision = "ec5d1c7ca9cf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
