"""test running migrations

Revision ID: 532ae1c53807
Revises: af019ca12c37
Create Date: 2024-07-04 21:30:30.845974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532ae1c53807'
down_revision = 'af019ca12c37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
