"""test running migrations

Revision ID: 583166e02061
Revises: 94fb3d6b2245
Create Date: 2024-08-27 15:07:18.093950

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "583166e02061"
down_revision = "94fb3d6b2245"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
