"""test running migrations

Revision ID: 6357d524190c
Revises: 1cc5e34afba6
Create Date: 2024-08-29 16:24:59.485161

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6357d524190c"
down_revision = "1cc5e34afba6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
