"""test running migrations

Revision ID: 64633cca05c1
Revises: 7a0cc7ef6662
Create Date: 2024-07-04 21:16:06.850065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64633cca05c1'
down_revision = '7a0cc7ef6662'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
