"""test running migrations

Revision ID: 6b052f8c3545
Revises: 07d22662fc7a
Create Date: 2024-07-04 21:39:14.067716

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6b052f8c3545"
down_revision = "07d22662fc7a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
