"""test running migrations

Revision ID: 748419f23c93
Revises: 197aaaa2a36f
Create Date: 2024-09-13 15:22:37.478993

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "748419f23c93"
down_revision = "197aaaa2a36f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
