"""test running migrations

Revision ID: 7a0cc7ef6662
Revises: deabbb714de3
Create Date: 2024-07-04 21:13:36.853445

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7a0cc7ef6662"
down_revision = "deabbb714de3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
