"""test running migrations

Revision ID: 80027a9c0134
Revises: 26320a953353
Create Date: 2024-08-26 14:37:12.029739

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "80027a9c0134"
down_revision = "26320a953353"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
