"""test running migrations

Revision ID: 80b0492139b0
Revises: 4ae93cf5b509
Create Date: 2024-09-13 15:23:56.226458

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "80b0492139b0"
down_revision = "4ae93cf5b509"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
