"""test running migrations

Revision ID: 8dd3a7adc931
Revises: fdd104b73e02
Create Date: 2024-09-09 16:18:21.972172

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "8dd3a7adc931"
down_revision = "fdd104b73e02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
