"""test running migrations

Revision ID: 8e6d36659027
Revises: b8122c4bff42
Create Date: 2024-08-27 14:53:22.550914

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "8e6d36659027"
down_revision = "b8122c4bff42"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
