"""test running migrations

Revision ID: 94fb3d6b2245
Revises: ae7ed56b54ef
Create Date: 2024-08-27 15:05:49.615666

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "94fb3d6b2245"
down_revision = "ae7ed56b54ef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
