"""test running migrations

Revision ID: 97ffc145ad49
Revises: 9a5abffcc860
Create Date: 2024-07-13 13:59:03.077045

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "97ffc145ad49"
down_revision = "9a5abffcc860"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
