"""test running migrations

Revision ID: 98f3f9f85560
Revises: fa1e2a294892
Create Date: 2024-07-04 20:56:30.241078

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "98f3f9f85560"
down_revision = "fa1e2a294892"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
