"""test running migrations

Revision ID: 99f80748d1ae
Revises: 523419c1423c
Create Date: 2024-07-04 21:48:58.203955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f80748d1ae'
down_revision = '523419c1423c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
