"""test running migrations

Revision ID: a8a757df6450
Revises: 99f80748d1ae
Create Date: 2024-07-04 21:50:44.772537

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a8a757df6450"
down_revision = "99f80748d1ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
