"""test running migrations

Revision ID: ab7468b92dbd
Revises: 6b052f8c3545
Create Date: 2024-07-04 21:41:19.470470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7468b92dbd'
down_revision = '6b052f8c3545'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
