"""test running migrations

Revision ID: ae7ed56b54ef
Revises: 2c77c90eb035
Create Date: 2024-08-27 15:04:50.208280

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ae7ed56b54ef"
down_revision = "2c77c90eb035"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
