"""test running migrations

Revision ID: af019ca12c37
Revises: 64633cca05c1
Create Date: 2024-07-04 21:20:54.925353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af019ca12c37'
down_revision = '64633cca05c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
