"""test running migrations

Revision ID: b2974f670ba4
Revises: 9dd0956d0c94
Create Date: 2024-06-25 16:52:02.909244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2974f670ba4'
down_revision = '9dd0956d0c94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
