"""test running migrations

Revision ID: b8122c4bff42
Revises: 80027a9c0134
Create Date: 2024-08-27 14:53:13.873225

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b8122c4bff42"
down_revision = "80027a9c0134"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
