"""test running migrations

Revision ID: bf32059127ad
Revises: fe511df8cdda
Create Date: 2024-07-13 13:45:01.376722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf32059127ad'
down_revision = 'fe511df8cdda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
