"""test running migrations

Revision ID: c02f926fad03
Revises: 3cada3b1b98f
Create Date: 2024-09-13 15:16:04.776943

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c02f926fad03"
down_revision = "3cada3b1b98f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
