"""test running migrations

Revision ID: c39ca4f6a308
Revises: eae6a6f7b0e1
Create Date: 2024-07-13 13:56:18.445847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39ca4f6a308'
down_revision = 'eae6a6f7b0e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
