"""test running migrations

Revision ID: c943208dccd4
Revises: 8dd3a7adc931
Create Date: 2024-09-13 14:45:54.895510

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c943208dccd4"
down_revision = "8dd3a7adc931"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
