"""test running migrations

Revision ID: d0293ebfdea5
Revises: e82dad78cb78
Create Date: 2024-08-29 16:30:44.444777

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d0293ebfdea5"
down_revision = "e82dad78cb78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
