"""test running migrations

Revision ID: d99a398551db
Revises: e53f97361d1a
Create Date: 2024-09-16 13:59:08.679454

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d99a398551db"
down_revision = "e53f97361d1a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
