"""test running migrations

Revision ID: e27d29f60a7e
Revises: 8fc0068783ea
Create Date: 2024-07-31 21:27:36.498560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27d29f60a7e'
down_revision = '8fc0068783ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
