"""test running migrations

Revision ID: e53f97361d1a
Revises: 80b0492139b0
Create Date: 2024-09-13 15:24:32.754537

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e53f97361d1a"
down_revision = "80b0492139b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
