"""test running migrations

Revision ID: e82dad78cb78
Revises: 2db40fa383c3
Create Date: 2024-08-29 16:29:31.785725

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e82dad78cb78"
down_revision = "2db40fa383c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
