"""test running migrations

Revision ID: ec5d1c7ca9cf
Revises: ab7468b92dbd
Create Date: 2024-07-04 21:41:57.680204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5d1c7ca9cf'
down_revision = 'ab7468b92dbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
