"""test running migrations

Revision ID: f5a1ce277426
Revises: c943208dccd4
Create Date: 2024-09-13 14:47:07.361243

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f5a1ce277426"
down_revision = "c943208dccd4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
