"""test running migrations

Revision ID: fa1e2a294892
Revises: b2974f670ba4
Create Date: 2024-06-25 16:52:17.014347

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "fa1e2a294892"
down_revision = "b2974f670ba4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
