"""test running migrations

Revision ID: fdd104b73e02
Revises: 0870e39ac45c
Create Date: 2024-09-09 16:02:55.905592

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "fdd104b73e02"
down_revision = "0870e39ac45c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
