"""test running migrations

Revision ID: fe511df8cdda
Revises: 13d013367322
Create Date: 2024-07-13 13:38:07.472868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe511df8cdda'
down_revision = '13d013367322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
